### ISSUE TITLE
npm ERR! Failed at the frontpage-polymer-app@ start script 'webpack-dev-server --inline --hot --port 3000'.

### ISSUE THREAD

**Issue by vedtam** [aruntk/polymer-apollo-frontpage#1]
Hi,

After cloning this repo, run install then npm start, I get the following error. What could be the issue?

```
c:polymer-apollo-frontpage vedtam$ npm start

> frontpage-polymer-app@ start /Users/vedtam/Sites/polymer-apollo-frontpage
> webpack-dev-server --inline --hot --port 3000

/Users/vedtam/Sites/polymer-apollo-frontpage/node_modules/webpack-dev-server/bin/webpack-dev-server.js:376
		throw e;
		^

TypeError: webpack.validateSchema is not a function
    at new Server (/Users/vedtam/Sites/polymer-apollo-frontpage/node_modules/webpack-dev-server/lib/Server.js:23:33)
    at startDevServer (/Users/vedtam/Sites/polymer-apollo-frontpage/node_modules/webpack-dev-server/bin/webpack-dev-server.js:369:12)
    at processOptions (/Users/vedtam/Sites/polymer-apollo-frontpage/node_modules/webpack-dev-server/bin/webpack-dev-server.js:307:3)
    at Object.<anonymous> (/Users/vedtam/Sites/polymer-apollo-frontpage/node_modules/webpack-dev-server/bin/webpack-dev-server.js:431:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)

npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/Users/vedtam/.npm-packages/bin/npm" "start"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE
npm ERR! frontpage-polymer-app@ start: `webpack-dev-server --inline --hot --port 3000`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the frontpage-polymer-app@ start script 'webpack-dev-server --inline --hot --port 3000'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the frontpage-polymer-app package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack-dev-server --inline --hot --port 3000
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs frontpage-polymer-app
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls frontpage-polymer-app
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/vedtam/Sites/polymer-apollo-frontpage/npm-debug.log
```

Full Log:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/Users/vedtam/.npm-packages/bin/npm',
1 verbose cli   'start' ]
2 info using npm@3.10.9
3 info using node@v6.9.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle frontpage-polymer-app@~prestart: frontpage-polymer-app@
6 silly lifecycle frontpage-polymer-app@~prestart: no script for prestart, continuing
7 info lifecycle frontpage-polymer-app@~start: frontpage-polymer-app@
8 verbose lifecycle frontpage-polymer-app@~start: unsafe-perm in lifecycle true
9 verbose lifecycle frontpage-polymer-app@~start: PATH: /Users/vedtam/.npm-packages/lib/node_modules/npm/bin/node-gyp-bin:/Users/vedtam/Sites/polymer-apollo-frontpage/node_modules/.bin:/Users/vedtam/.npm-packages/bin:/usr/local/php5/bin:/usr/local/php5/bin:/Users/vedtam/.composer/vendor/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/opt/X11/bin
10 verbose lifecycle frontpage-polymer-app@~start: CWD: /Users/vedtam/Sites/polymer-apollo-frontpage
11 silly lifecycle frontpage-polymer-app@~start: Args: [ '-c', 'webpack-dev-server --inline --hot --port 3000' ]
12 silly lifecycle frontpage-polymer-app@~start: Returned: code: 1  signal: null
13 info lifecycle frontpage-polymer-app@~start: Failed to exec start script
14 verbose stack Error: frontpage-polymer-app@ start: `webpack-dev-server --inline --hot --port 3000`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/Users/vedtam/.npm-packages/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/Users/vedtam/.npm-packages/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid frontpage-polymer-app@
16 verbose cwd /Users/vedtam/Sites/polymer-apollo-frontpage
17 error Darwin 15.6.0
18 error argv "/usr/local/bin/node" "/Users/vedtam/.npm-packages/bin/npm" "start"
19 error node v6.9.1
20 error npm  v3.10.9
21 error code ELIFECYCLE
22 error frontpage-polymer-app@ start: `webpack-dev-server --inline --hot --port 3000`
22 error Exit status 1
23 error Failed at the frontpage-polymer-app@ start script 'webpack-dev-server --inline --hot --port 3000'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the frontpage-polymer-app package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     webpack-dev-server --inline --hot --port 3000
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs frontpage-polymer-app
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls frontpage-polymer-app
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by aruntk** [comment]
@vedtam It was due to a peer dependency conflict. Check it now.

**Comment by vedtam** [comment]
@aruntk trying on a different machine, same error:

```
vedtam@vedtam-K52Jc:~/test/polymer-apollo-frontpage$ sudo npm start

> frontpage-polymer-app@ start /home/vedtam/test/polymer-apollo-frontpage
> webpack-dev-server --inline --hot --port 3000

module.js:328
    throw err;
    ^

Error: Cannot find module 'webpack'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/vedtam/test/polymer-apollo-frontpage/node_modules/webpack-dev-server/lib/Server.js:13:15)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)

npm ERR! Linux 4.4.0-45-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! frontpage-polymer-app@ start: `webpack-dev-server --inline --hot --port 3000`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the frontpage-polymer-app@ start script 'webpack-dev-server --inline --hot --port 3000'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the frontpage-polymer-app package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack-dev-server --inline --hot --port 3000
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs frontpage-polymer-app
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls frontpage-polymer-app
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/vedtam/test/polymer-apollo-frontpage/npm-debug.log
```

**Comment by vedtam** [comment]
@aruntk trying in another machine (ubuntu 16) error:

By the way, I have webpack installed globally as welll.

```
npm start

> frontpage-polymer-app@ start /home/vedtam/test/polymer-apollo-frontpage
> webpack-dev-server --inline --hot --port 3000

module.js:328
    throw err;
    ^

Error: Cannot find module 'webpack'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/vedtam/test/polymer-apollo-frontpage/node_modules/webpack-dev-server/lib/Server.js:13:15)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)

npm ERR! Linux 4.4.0-45-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! frontpage-polymer-app@ start: `webpack-dev-server --inline --hot --port 3000`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the frontpage-polymer-app@ start script 'webpack-dev-server --inline --hot --port 3000'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the frontpage-polymer-app package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack-dev-server --inline --hot --port 3000
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs frontpage-polymer-app
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls frontpage-polymer-app
npm ERR! There is likely additional logging output above.
npm ERR! Linux 4.4.0-45-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! path npm-debug.log.178046125
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall open

npm ERR! Error: EACCES: permission denied, open 'npm-debug.log.178046125'
npm ERR!     at Error (native)
npm ERR!  { [Error: EACCES: permission denied, open 'npm-debug.log.178046125']
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'open',
npm ERR!   path: 'npm-debug.log.178046125' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/vedtam/test/polymer-apollo-frontpage/npm-debug.log
```

**Comment by vedtam** [comment]
hello @aruntk,

Sorry for bothering, I have spent a whole day trying to get this project work but without luck. Now when I clone this repo and try to start it I get:

```
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.15
npm WARN babel-loader@6.2.7 requires a peer of webpack@1 || ^2.1.0-beta but none was installed.
npm WARN webpack-dev-server@2.1.0-beta.11 requires a peer of webpack@^2.1.0-beta.26 but none was installed.
npm WARN webpack-dev-middleware@1.8.4 requires a peer of webpack@1 || ^2.1.0-beta but none was installed.
vedtam@vedtam-K52Jc:~/test/polimer-apollo/polymer-apollo-frontpage$ sudo npm start

> frontpage-polymer-app@ start /home/vedtam/test/polimer-apollo/polymer-apollo-frontpage
> webpack-dev-server --inline --hot --port 3000

module.js:328
    throw err;
    ^

Error: Cannot find module 'webpack'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/vedtam/test/polimer-apollo/polymer-apollo-frontpage/node_modules/webpack-dev-server/lib/Server.js:13:15)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)

npm ERR! Linux 4.4.0-47-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! frontpage-polymer-app@ start: `webpack-dev-server --inline --hot --port 3000`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the frontpage-polymer-app@ start script 'webpack-dev-server --inline --hot --port 3000'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the frontpage-polymer-app package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack-dev-server --inline --hot --port 3000
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs frontpage-polymer-app
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls frontpage-polymer-app
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/vedtam/test/polimer-apollo/polymer-apollo-frontpage/npm-debug.log

```
